# Generated by Django 3.2.9 on 2022-02-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodid', models.IntegerField()),
                ('fooditem', models.CharField(max_length=50)),
                ('calorie', models.IntegerField()),
            ],
        ),
    ]
